//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myIRproj
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistinctkGramsIndex
    {
        public string k_gram { get; set; }
        public string terms { get; set; }
    }
}
